name: master
on:
  push:
    branches:
      - 'develop'
      - 'master'
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - 'feature/**'
      - 'develop'
jobs:
  build:
    name: develop build
    runs-on: macos-latest
    timeout-minutes: 30
    env:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
        xcode-version: '13.4.1'
      - uses: actions/checkout@v3
      - name: Build
        run: xcodebuild -project UDF.xcodeproj
      - name: Test
        run: xcodebuild test -project UDF.xcodeproj -scheme UDF -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.5'
